# Generated by Django 4.0 on 2021-12-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザー'},
        ),
    ]
