# Generated by Django 4.0 on 2022-01-12 07:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名は既に使用されています。'}, help_text='16文字以下の英数字、@/./+/-/_のみ使用できます。', max_length=16, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザ名'),
        ),
    ]
