# Generated by Django 4.0 on 2022-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'このメールアドレスは既に使用されています。'}, max_length=254, null=True, unique=True, verbose_name='Eメールアドレス'),
        ),
    ]
