# Generated by Django 4.0 on 2022-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='これを選択すると、スタッフとして権限が付与されます。', verbose_name='権限ステータス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='これを選択すると、管理者として管理権限が付与されます。', verbose_name='管理者ステータス'),
        ),
    ]
