# Generated by Django 4.0 on 2021-12-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='255文字まで使用できます。', max_length=255, verbose_name='問題文')),
                ('answer', models.CharField(help_text='255文字まで使用できます。', max_length=255, verbose_name='解答')),
                ('answer_yomi', models.CharField(help_text='255文字まで使用できます。', max_length=255, verbose_name='解答読み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_seen', models.IntegerField(default=0, help_text='問題が出題された人数。', verbose_name='会問人数')),
                ('n_pushed', models.IntegerField(default=0, help_text='ボタンを押して回答の権利を得た人数。', verbose_name='獲答権人数')),
                ('n_through', models.IntegerField(default=0, help_text='ボタンを押す権利があっても押さなかった人数。', verbose_name='棄答権人数')),
                ('n_stolen', models.IntegerField(default=0, help_text='出題時のルールで定められた回答の権利が埋まり，ボタンを押す権利を無くした人数。', verbose_name='埋答人数')),
                ('n_correct', models.IntegerField(default=0, help_text='会問した人のうち，正答した人数。', verbose_name='正答人数')),
                ('n_uncorrect', models.IntegerField(default=0, help_text='会問した人のうち，誤答した人数。', verbose_name='誤答人数')),
                ('is_draft', models.BooleanField(default=True, help_text='選択しているなら，下書きです。', verbose_name='下書き状況')),
                ('is_publish', models.BooleanField(default=True, help_text='選択しているなら，公開されています。', verbose_name='公開状況')),
                ('is_official', models.BooleanField(default=True, help_text='選択しているなら，公式問題です。', verbose_name='公式状況')),
                ('author', models.ForeignKey(default='QUIZ MAN', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='GoodQuix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='BetaMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
