# Generated by Django 4.0 on 2021-12-20 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodQuix',
            new_name='GoodQuiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='n_seen',
            new_name='n_encount',
        ),
        migrations.AddField(
            model_name='quiz',
            name='n_checked',
            field=models.IntegerField(default=0, help_text='この問題の詳細画面を確認した人数。', verbose_name='詳細閲覧回数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_yomi',
            field=models.CharField(help_text='全角ひらがな255文字まで使用できます。', max_length=255, validators=[django.core.validators.RegexValidator(message='全角のひらがなで入力してください。', regex='^[ぁ-ん]')], verbose_name='解答かな'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_official',
            field=models.BooleanField(default=False, help_text='選択しているなら，公式問題です。', verbose_name='公式状況'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_publish',
            field=models.BooleanField(default=False, help_text='選択しているなら，公開されています。', verbose_name='公開状況'),
        ),
    ]
