# Generated by Django 4.0 on 2021-12-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quiz_n_pushed_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='n_pushed_place',
            field=models.TextField(default='[]', help_text='n文字目でボタンが押された回数', verbose_name='毎スラッシュ押数'),
        ),
    ]
