# Generated by Django 4.0 on 2021-12-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_quiz_n_pushed_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='n_pushed_place',
        ),
        migrations.AddField(
            model_name='quiz',
            name='_n_pushed_place',
            field=models.TextField(default='[]', help_text='n文字目でボタンが押された回数。json形式で保存', verbose_name='毎スラッシュ押数'),
        ),
    ]
