# Generated by Django 4.0 on 2021-12-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_quiz_n_pushed_place_quiz__n_pushed_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='n_checked',
            field=models.PositiveIntegerField(default=0, help_text='この問題の詳細画面を確認した人数。', verbose_name='詳細閲覧回数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='n_correct',
            field=models.PositiveIntegerField(default=0, help_text='会問した人のうち，正答した人数。', verbose_name='正答人数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='n_encount',
            field=models.PositiveIntegerField(default=0, help_text='問題が出題された人数。', verbose_name='会問人数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='n_pushed',
            field=models.PositiveIntegerField(default=0, help_text='ボタンを押して回答の権利を得た人数。', verbose_name='獲答権人数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='n_stolen',
            field=models.PositiveIntegerField(default=0, help_text='出題時のルールで定められた回答の権利が埋まり，ボタンを押す権利を無くした人数。', verbose_name='埋答人数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='n_through',
            field=models.PositiveIntegerField(default=0, help_text='ボタンを押す権利があっても押さなかった人数。', verbose_name='棄答権人数'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='n_uncorrect',
            field=models.PositiveIntegerField(default=0, help_text='会問した人のうち，誤答した人数。', verbose_name='誤答人数'),
        ),
        migrations.CreateModel(
            name='Slash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_all', models.TextField(help_text='スラッシュ直前までの問題文', verbose_name='スラッシュ文')),
                ('before_just', models.CharField(help_text='スラッシュ直前の一文字', max_length=1, verbose_name='スラッシュ文字')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
            ],
        ),
    ]
