# Generated by Django 4.0 on 2021-12-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_slash_slash_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='_n_pushed_place',
        ),
        migrations.AddField(
            model_name='slash',
            name='n_push',
            field=models.PositiveIntegerField(default=0, help_text='このスラッシュでボタンが押された数', verbose_name='押ボタン数'),
        ),
    ]
