# Generated by Django 4.0 on 2021-12-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_quiz__n_pushed_place_slash_n_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='slash',
            name='n_correct',
            field=models.PositiveIntegerField(default=0, help_text='このスラッシュでボタンを押した人のうち，正答した人数。', verbose_name='正答人数'),
        ),
        migrations.AddField(
            model_name='slash',
            name='n_uncorrect',
            field=models.PositiveIntegerField(default=0, help_text='このスラッシュでボタンを押した人のうち，誤答した人数。', verbose_name='誤答人数'),
        ),
        migrations.AlterField(
            model_name='slash',
            name='n_push',
            field=models.PositiveIntegerField(default=0, help_text='このスラッシュでボタンが押された数', verbose_name='押ボタン人数'),
        ),
    ]
