# Generated by Django 4.0 on 2022-01-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_slash_n_correct_slash_n_uncorrect_alter_slash_n_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='選択しているなら，下書きです。', verbose_name='下書き状況'),
        ),
    ]
