# Generated by Django 4.0 on 2022-02-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_email'),
        ('app', '0011_alter_betamon_quiz_alter_betamon_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betamon',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betamon', to='app.quiz'),
        ),
        migrations.AlterField(
            model_name='betamon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betamon', to='users.user'),
        ),
        migrations.AlterField(
            model_name='goodquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_quiz', to='app.quiz'),
        ),
        migrations.AlterField(
            model_name='goodquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_quiz', to='users.user'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='選択しているなら，下書きです。', verbose_name='下書き'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_official',
            field=models.BooleanField(default=False, help_text='選択しているなら，公式問題です。', verbose_name='公式'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_publish',
            field=models.BooleanField(default=True, help_text='選択しているなら，公開されています。管理者のみ変更可能。強制的に非公開に変更する場合にチェックを外す。', verbose_name='公開'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
