# Generated by Django 4.0 on 2022-02-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quiz_is_todays_question_alter_quiz_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_todays_question',
            field=models.BooleanField(default=False, help_text='選択されていたら、今日の一問に表示されます。複数選択されていても、indexでは一問のみ表示されます。', verbose_name='今日の一問'),
        ),
        migrations.AlterField(
            model_name='slash',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slash', to='app.quiz'),
        ),
    ]
