# Generated by Django 4.0 on 2022-03-08 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_email'),
        ('app', '0014_alter_quiz_is_todays_question_alter_slash_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer_yomi',
            field=models.CharField(help_text='全角ひらがな255文字まで使用できます。', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='全角のひらがなで入力してください。', regex='^[ぁ-ん]')], verbose_name='解答かな'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(default='QUIZ MAN', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='quiz', to='users.user'),
        ),
    ]
