# Generated by Django 4.0 on 2022-03-28 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_quiz_answer_yomi_alter_quiz_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer_yomi',
            field=models.CharField(blank=True, help_text='全角ひらがな255文字まで使用できます。', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='全角のひらがなで入力してください。', regex='^[ぁ-ん]')], verbose_name='解答かな'),
        ),
    ]
